apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: system
---
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: system
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: controller-manager-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /manager
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CONCOURSECI_FLY_PATH
            value: "/fly"
          - name: SECRET_NAME
            value: $(WEBHOOK_SECRET_NAME)
          - name: CONCOURSECI_URL
            valueFrom:
              secretKeyRef:
                name: controller-manager
                key: CONCOURSECI_URL
          - name: CONCOURSECI_TARGET
            valueFrom:
              secretKeyRef:
                name: controller-manager
                key: CONCOURSECI_TARGET
          - name: CONCOURSECI_TEAM
            valueFrom:
              secretKeyRef:
                name: controller-manager
                key: CONCOURSECI_TEAM
          - name: CONCOURSECI_USERNAME
            valueFrom:
              secretKeyRef:
                name: controller-manager
                key: CONCOURSECI_USERNAME
          - name: CONCOURSECI_PASSWORD
            valueFrom:
              secretKeyRef:
                name: controller-manager
                key: CONCOURSECI_PASSWORD
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-secret
  namespace: system
